export const PERMISSIONS = [
  "CLIENT_VIEW",
  "CLIENT_SUSPEND",
  "KYC_VIEW",
  "KYC_APPROVE",
  "KYC_REJECT",
  "KYC_REQUEST_UPDATE",
  "FEE_VIEW",
  "FEE_MANAGE",
  "WALLET_VIEW",
  "WALLET_ADJUST",
  "DEPOSIT_VIEW",
  "WITHDRAWAL_VIEW",
  "WITHDRAWAL_APPROVE",
  "WITHDRAWAL_REJECT",
  "MUDARABAH_CREATE",
  "MUDARABAH_APPROVE",
  "MUDARABAH_PUBLISH",
  "IJARAH_CREATE",
  "IJARAH_APPROVE",
  "IJARAH_PUBLISH",
  "DISTRIBUTION_CREATE",
  "DISTRIBUTION_APPROVE",
  "DISTRIBUTION_EXECUTE",
  "REPORT_VIEW",
  "REPORT_EXPORT",
  "ADMIN_MANAGE",
  "SETTINGS_MANAGE",
  "AUDIT_VIEW",
  "TICKET_MANAGE",
  "NOTIFICATION_SEND",
  "DOCUMENT_REVIEW",
  "RECONCILIATION_VIEW",
] as const;

export type PermissionName = (typeof PERMISSIONS)[number];

const ALL = new Set<PermissionName>(PERMISSIONS);

export const ROLE_GRANTS: Record<string, Set<PermissionName>> = {
  SUPER_ADMIN: ALL,
  COMPLIANCE_ADMIN: new Set(["CLIENT_VIEW", "KYC_VIEW", "KYC_APPROVE", "KYC_REJECT", "KYC_REQUEST_UPDATE", "DOCUMENT_REVIEW"]),
  INVESTMENT_ADMIN: new Set([
    "CLIENT_VIEW",
    "MUDARABAH_CREATE",
    "MUDARABAH_PUBLISH",
    "IJARAH_CREATE",
    "IJARAH_PUBLISH",
    "DISTRIBUTION_CREATE",
    "REPORT_VIEW",
  ]),
  FINANCE_ADMIN: new Set([
    "CLIENT_VIEW",
    "FEE_VIEW",
    "FEE_MANAGE",
    "WALLET_VIEW",
    "WALLET_ADJUST",
    "DEPOSIT_VIEW",
    "WITHDRAWAL_VIEW",
    "WITHDRAWAL_APPROVE",
    "WITHDRAWAL_REJECT",
    "DISTRIBUTION_APPROVE",
    "DISTRIBUTION_EXECUTE",
    "REPORT_VIEW",
    "REPORT_EXPORT",
    "RECONCILIATION_VIEW",
  ]),
  SUPPORT_ADMIN: new Set(["CLIENT_VIEW", "TICKET_MANAGE", "NOTIFICATION_SEND", "DEPOSIT_VIEW"]),
};

export function roleHas(role: string | null | undefined, permission: PermissionName) {
  if (!role) return false;
  return ROLE_GRANTS[role]?.has(permission) ?? false;
}
